version: "3.8"

services:
  node-server:
    build: .
    container_name: "first-node-compose"
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mongo
    container_name: "mongodb-container"
    ports:
      - 27017:27017
    volumes:
      - my-vol:/data/db

volumes:
  my-vol:
